name: Build MeowCatCompress
on:
  workflow_dispatch:

jobs:
  build:
    name: Build MeowCatCompress
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - qt_ver: 6.5.3
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    env:
      targetName: MeowCatCompress.exe
      fileName: MeowCatCompress
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Install pip packages
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install "PySide6-Fluent-Widgets[full]"
          python -m pip install pyinstaller

      - name: Package with PyInstaller
        env:
          archiveName: ${{ env.fileName }}-${{ matrix.qt_arch }}-${{ matrix.qt_ver }}
          msvcArch: ${{ matrix.msvc_arch }}
        shell: pwsh
        run: |
          pyinstaller -w ./meowcatcompress.py -n MeowCatCompress
          xcopy /s /e /y data\qss\ dist\MeowCatCompress\data\qss\
          xcopy /s /e /y data\image\ dist\MeowCatCompress\data\image\
          xcopy /s /e /y data\translate\ dist\MeowCatCompress\data\translate\

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.fileName }}
          path: dist
